version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: book_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bookdb
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  bookstore:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bookstore_app
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_HOST: book_db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: bookdb
      DB_PORT: 5432
      DB_SSLMODE: disable
    depends_on:
      - postgres

volumes:
  pg_data: